### ISSUE TITLE
Command line error 127, function () { [native code] }

### ISSUE THREAD

**Issue by THE-SIMPLE-MARK** [nokkvireyr/steamcmd-node#1]
I've encountered this bug on my hosting provider which runs on `debian-buster-slim`, it works fine on Windows, but I get the following error on my provider:
```
Error: Command line error 127, function () { [native code] }
at SteamCMD.execRaw (file:///app/node_modules/steamcmd-node/dist/mjs/index.js:61:23)
at async handler (/app/.next/server/pages/api/getWorkshopCreation.js:137:9)
at async /app/node_modules/@sentry/nextjs/cjs/utils/withSentry.js:95:29
at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:366:9)
at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:481:9)
at async Object.fn (/app/node_modules/next/dist/server/next-server.js:735:37)
at async Router.execute (/app/node_modules/next/dist/server/router.js:247:36)
at async NextNodeServer.run (/app/node_modules/next/dist/server/base-server.js:347:29)
at async NextNodeServer.handleRequest (/app/node_modules/next/dist/server/base-server.js:285:20)
```

The error seems to be generated at this line:
https://github.com/nokkvireyr/steamcmd-node/blob/master/src/index.ts#L67

Help would be greately appreciated as I have no clue how to solve this.

**Comment by THE-SIMPLE-MARK** [comment]
After reading the stream attached to the error I realized it meant that the command was not found due to a missing library on linux. The stream had the following error:
`qemu-i386: Could not open '/lib/ld-linux.so.2': No such file or directory`

After searching for a library on the Debian package search website, I came to the conclusion that the library `libc6-i386` was a perfect match to fix this issue.

Hope this helps someone with the same issue as me.
